### ISSUE TITLE
Seasons not working

### ISSUE THREAD

**Issue by tux2000** [Ikosse/plugin.video.teliaplay-se#10]
Hej,

installed the plugin today (version 1.2.7). Cant browse the content of any season of any show. The most recent episode is possible to play.

Error message:

```
2023-03-27 19:55:39.606 T:18131   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'getSeason'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/addon.py", line 5, in <module>
                                                       plugin.run()
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/resources/lib/plugin.py", line 109, in run
                                                       router.main_menu()
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/resources/lib/plugin.py", line 30, in main_menu
                                                       self.menu_list.season_menu(self.params["seasonId"])
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/resources/lib/menus.py", line 34, in wrapped_method_call
                                                       retval = method(*args, **kwargs)
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/resources/lib/menus.py", line 914, in season_menu
                                                       episodes = self.telia_play.get_season(season_id)
                                                     File "/home/pi/.kodi/addons/plugin.video.teliaplay-se/resources/lib/api.py", line 457, in get_season
                                                       "sha256Hash": self.graphql_hashes["getSeason"]
                                                   KeyError: 'getSeason'
                                                   -->End of Python script error report<--

2023-03-27 19:55:39.709 T:18131    INFO <general>: Python interpreter stopped
2023-03-27 19:55:39.723 T:18130   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.teliaplay-se/?menu=season&seasonId=s-34268_15
2023-03-27 19:55:39.738 T:17999   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.teliaplay-se/?menu=season&seasonId=s-34268_15) failed


```

**Comment by tux2000** [comment]
solved by #11
